a = input('Digite algo: ')
print(f'O tipo primitivo dele é {type(a)}')
print(f'Só tem espaço? {a.isspace()}')
print(f'É um número? {a.isnumeric()}')
print(f'É um alfabetico? {a.isalpha()}')
print(f'É alfanumerico? {a.isalnum()}')
print(f'É maiúsculas? {a.isupper()}')
print(f'É minúsculas? {a.islower()}')
print(f'Está capitalizada? {a.istitle()}')